version: '3.8'
services:
  cct-app:
    depends_on:
      - cct-db
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  cct-db:
    image: mysql:8.0.29
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
volumes:
  db: